title: Zhifei Yang
subtitle: System Software Engineer @ ByteDance
email: xividyzf@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I am a systems software engineer and researcher. 
  I am interested in the art of computer systems design and implementation. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zhifei.me" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: zhifei_yang
github_username:  xivid
linkedin_username: yangzhifei
google_analytics: UA-85444455-2

# Build settings
remote_theme: xivid/jekyll-theme-fibonacci
plugins:
  - jekyll-remote-theme
  - jekyll-feed
