---
title: Zhifei Yang
timezone: UTC
collections:
  activities:
    title: Activities
    output: true
    permalink: "/activities/:path/"
  news:
    title: News
    output: false
    permalink: "/news/:path/"
    defaults:
      layout: post
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/projects/:path/"
  teaching:
    title: Teaching
    output: true
    permalink: "/teaching/:path/"
  uploads:
    title: Uploads
    output: true
name: Zhifei Yang
email: zhiyang@ethz.ch
description: I am a Computer Science graduate student at ETH Zürich, focusing on distributed
  systems research.
url: 
baseurl: 
last_updated: May 22, 2018
github_username: Xivid
twitter_username: 
linkedin_username: yangzhifei
scholar_userid: 
orcid_id: 
contact_note: 
google_analytics: UA-85444455-2
news_limit: 5
markdown: kramdown
highlighter: pygments
include:
- _pages
- CNAME
plugins:
- jekyll-email-protect
- jekyll/scholar
- jemoji
scholar:
  last_name: Yang
  style: apa
  locale: en
  sort_by: year
  order: descending
  source: "/_bibliography/"
  bibliography: papers.bib
  bibliography_template: bib
  replace_strings: true
  join_strings: true
  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details
  query: "@*"
jquery_version: 1.12.4
katex_version: 0.9.0
anchorjs_version: 3.2.2
