---
title: Xivid.Github.Io
timezone: UTC
collections:
  news:
    title: News
    output: true
    permalink: "/news/:path/"
    defaults:
      layout: post
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/projects/:path/"
  uploads:
    title: Uploads
    output: true
name: Zhifei Yang
email: zhiyang@ethz.ch
description: I am a Computer Science graduate student at ETH Zürich, focusing on distributed
  systems research.
footer_text: Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a>
  with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme. Hosted
  by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
url: https://zhifei.me
baseurl: 
last_updated: May 22, 2018
github_username: Xivid
twitter_username: 
linkedin_username: yangzhifei
scholar_userid: 
orcid_id: 
contact_note: 
google_analytics: UA-85444455-2
blog_name: Techdemics
blog_description: Technology meets academics
paginate: 4
permalink: "/blog/:year/:title/"
paginate_path: "/blog/page:num/"
text:
  pagination:
    newer: Newer
    older: Older
disqus_shortname: xivid
show_social_icons: false
enable_anchorjs: false
enable_katex: true
news_limit: 5
markdown: kramdown
highlighter: pygments
include:
- _pages
plugins:
- jekyll-email-protect
- jekyll-paginate
- jekyll/scholar
- jemoji
scholar:
  last_name: Einstein
  style: apa
  locale: en
  sort_by: year
  order: descending
  source: "/_bibliography/"
  bibliography: papers.bib
  bibliography_template: bib
  replace_strings: true
  join_strings: true
  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details
  query: "@*"
jquery_version: 1.12.4
katex_version: 0.9.0
anchorjs_version: 3.2.2
